[package]
name = "HuffmanDecoder"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
tracing = "0.1"
tracing-chrome = "0.7"
tracing-subscriber = "0.3"
criterion = "0.5.1"

[[bench]]
name = "stock_parser_benchmark"
harness = false

[profile.release]
debug = true